{
  pkgs,
  lib,
  deps,
  utils,
  desktop,
  services,
  signing,
  drv,
  format,
  meta,
  target,
}:

let
  common = import ./_common-linux.nix {
    inherit
      pkgs
      lib
      deps
      utils
      desktop
      services
      ;
  };
  pkgArch = meta.archArch;
  reqs = meta.depends.archlinux or [ ];
  optDeps = meta.depends.archlinuxOptional or [ ];

  mode = meta.archlinux.output;
  wantPkg = mode == "pkg" || mode == "both";
  wantAur = mode == "aur" || mode == "both";

  aurPkgname = "${meta.name}-bin";
  aurTarName = "${aurPkgname}-${meta.version}-${pkgArch}.tar.gz";
  # `meta.downloadUrl` is a directory prefix (same contract as the
  # installer / install.md use of `releaseUrl`). Append the tarball
  # filename so PKGBUILD's `source=()` resolves to a real asset URL.
  downloadUrl =
    if meta.downloadUrl != "" then
      "${meta.downloadUrl}/${aurTarName}"
    else
      "https://example.com/releases/${aurTarName}";

  # Where the AUR files live relative to $out:
  # - mode = "aur"  → directly in $out
  # - mode = "both" → in $out/aur (alongside the .pkg.tar.zst)
  aurDirVar = if mode == "aur" then "$out" else "$out/aur";

  installScript = lib.optionalString (common.needsPostScripts meta) ''
    post_install() {
      ${common.postinstSnippet meta}
    }
    post_upgrade() {
      ${common.postinstSnippet meta}
    }
    pre_remove() {
      ${common.prermSnippet meta}
    }
    post_remove() {
      ${common.postrmSnippet meta}
    }
  '';

  pkgTopLevelDirs = common.stageTopLevelDirs meta;
  packageCopyLines = lib.concatMapStringsSep "\n      " (
    d: ''cp -a "\$srcdir/${d}" "\$pkgdir/"  2>/dev/null || true''
  ) pkgTopLevelDirs;

  depsArr = lib.concatMapStringsSep " " (d: "'" + d + "'") reqs;
  optDepsArr = lib.concatMapStringsSep " " (d: "'" + d + "'") optDeps;

  drvName =
    if mode == "aur" then
      "${aurPkgname}-${meta.version}-${pkgArch}.aur"
    else
      "${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst";

  pkgBlock = lib.optionalString wantPkg ''
    instSize=$(${pkgs.coreutils}/bin/du -sb "$stage" | ${pkgs.coreutils}/bin/cut -f1)
    builddate=$(date +%s)

    ${lib.optionalString meta.autoDepends (
      deps.discoverLinuxDepsSnippet {
        kind = "archlinux";
        scanDirs = [
          "$stage/opt/${meta.name}/bin"
          "$stage/opt/${meta.name}/lib"
        ];
        userDeps = reqs;
        outFile = "arch-depends.csv";
      }
    )}

    {
      echo "# Generated by nix-bundle-app"
      echo "pkgname = ${meta.name}"
      echo "pkgbase = ${meta.name}"
      echo "pkgver = ${meta.version}-1"
      echo "pkgdesc = ${meta.summary}"
      echo "url = ${meta.homepage}"
      echo "builddate = $builddate"
      echo "packager = ${meta.maintainer}"
      echo "size = $instSize"
      echo "arch = ${pkgArch}"
      echo "license = ${meta.license}"
      ${
        if meta.autoDepends then
          ''
            if [ -s arch-depends.csv ]; then
              tr ',' '\n' < arch-depends.csv | while read -r d; do
                [ -n "$d" ] && echo "depend = $d"
              done
            fi
          ''
        else
          lib.concatMapStrings (d: ''
            echo "depend = ${d}"
          '') reqs
      }
      ${lib.concatMapStrings (d: ''
        echo "optdepend = ${d}"
      '') optDeps}
    } > "$stage/.PKGINFO"

    ${lib.optionalString (common.needsPostScripts meta) ''
      cp ${pkgs.writeText "${meta.name}.install" installScript} "$stage/.INSTALL"
      ${pkgs.gnused}/bin/sed -i 's/install = .*/&\ninstall = ${meta.name}.install/' "$stage/.PKGINFO" || true
    ''}

    (
      cd "$stage"
      mtree_extra=""
      [ -f .INSTALL ] && mtree_extra=".INSTALL"
      LANG=C bsdtar -cf - --format=mtree \
        --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' \
        .PKGINFO $mtree_extra * | ${pkgs.gzip}/bin/gzip -n -9 > .MTREE
    )

    out_pkg="$out/${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst"
    (
      cd "$stage"
      tar_extra=""
      [ -f .INSTALL ] && tar_extra=".INSTALL"
      LANG=C bsdtar --no-fflags -cf - .PKGINFO .MTREE $tar_extra * \
        | ${pkgs.zstd}/bin/zstd -19 -T0 -o "$out_pkg"
    )
  '';

  aurBlock = lib.optionalString wantAur ''
    aurDir=${aurDirVar}
    mkdir -p "$aurDir"

    aurStage=$PWD/aur-stage
    rm -rf "$aurStage"
    mkdir -p "$aurStage"
    ( cd "$stage" && ${pkgs.coreutils}/bin/cp -a --no-preserve=ownership . "$aurStage/" )
    rm -f "$aurStage/.PKGINFO" "$aurStage/.MTREE" "$aurStage/.INSTALL"

    aurTar="$aurDir/${aurTarName}"
    ( cd "$aurStage" && ${pkgs.gnutar}/bin/tar --owner=0 --group=0 --sort=name \
        -czf "$aurTar" . )

    aurSha=$(${pkgs.coreutils}/bin/sha256sum "$aurTar" | ${pkgs.coreutils}/bin/cut -d' ' -f1)

    cat > "$aurDir/PKGBUILD" <<EOF
    # Maintainer: ${meta.maintainer}
    pkgname=${aurPkgname}
    _pkgname=${meta.name}
    pkgver=${meta.version}
    pkgrel=1
    pkgdesc='${meta.summary}'
    arch=('${pkgArch}')
    url='${meta.homepage}'
    license=('${meta.license}')
    depends=(${depsArr})
    ${lib.optionalString (optDeps != [ ]) "optdepends=(${optDepsArr})"}
    provides=("\''${_pkgname}=\''${pkgver}")
    conflicts=("\''${_pkgname}")
    source=("${downloadUrl}")
    sha256sums=("$aurSha")
    ${lib.optionalString (common.needsPostScripts meta) "install=${aurPkgname}.install"}

    package() {
      ${packageCopyLines}
    }
    EOF
    ${pkgs.gnused}/bin/sed -i 's/^    //' "$aurDir/PKGBUILD"

    ${lib.optionalString (common.needsPostScripts meta) ''
      cp ${pkgs.writeText "${aurPkgname}.install" installScript} "$aurDir/${aurPkgname}.install"
    ''}

    {
      echo "pkgbase = ${aurPkgname}"
      echo "	pkgdesc = ${meta.summary}"
      echo "	pkgver = ${meta.version}"
      echo "	pkgrel = 1"
      echo "	url = ${meta.homepage}"
      echo "	arch = ${pkgArch}"
      echo "	license = ${meta.license}"
      ${lib.concatMapStrings (d: ''
        echo "	depends = ${d}"
      '') reqs}
      ${lib.concatMapStrings (d: ''
        echo "	optdepends = ${d}"
      '') optDeps}
      echo "	provides = ${meta.name}=${meta.version}"
      echo "	conflicts = ${meta.name}"
      echo "	source = ${downloadUrl}"
      echo "	sha256sums = $aurSha"
      ${lib.optionalString (common.needsPostScripts meta) ''
        echo "	install = ${aurPkgname}.install"
      ''}
      echo ""
      echo "pkgname = ${aurPkgname}"
    } > "$aurDir/.SRCINFO"
  '';
in
pkgs.stdenv.mkDerivation {
  name = drvName;
  dontUnpack = true;
  nativeBuildInputs = with pkgs; [
    libarchive
    zstd
    gzip
    gnutar
    patchelf
    file
    gnugrep
    rsync
    coreutils
    gnused
    gawk
    findutils
  ];

  buildCommand = ''
    stage=$PWD/stage
    mkdir -p "$stage"

    ${common.stageLinux {
      inherit drv meta target;
      stage = "$stage";
    }}

    mkdir -p $out

    ${pkgBlock}

    ${aurBlock}

    ${signing.emitSignScript {
      inherit meta format;
      artifactGlob = "*.pkg.tar.zst";
    }}
  '';

  passthru = {
    info = meta;
    inherit target format;
    archlinuxMode = mode;
    outFile =
      if mode == "aur" then "PKGBUILD" else "${meta.name}-${meta.version}-1-${pkgArch}.pkg.tar.zst";
  };
}
